### PR TITLE
5 0

### PR DESCRIPTION
**Pull request by bridget-pangburn**
These files have been reworded to work with Castle.  Screenshots are also included.

### CODE REVIEW

**Comment by tkimnguyen** [comment]
Please restore (but comment out) the robotframework bits... Also (perhaps jokingly) am wondering if it would make sense to define a variable like CMSNAME and set it to "Plone" by default but here set it to "Castle"...

**Comment by tkimnguyen** [comment]
@bridget-pangburn are you still planning to restore the screenshot bits?

**Comment by bridget-pangburn** [comment]
Yes. I should have everything up by the end of the week.

**Comment by tkimnguyen** [comment]
Thanks @bridget-pangburn !

**Pull request merged**
